import Live2DModel from '@/core/live2d/Live2DModel';
import Ticker from '@/core/mka/Ticker';
import { Renderer, Texture } from '@pixi/core';
import { Container } from '@pixi/display';
import { Sprite } from '@pixi/sprite';

interface Live2DSprite {
    emit(event: 'hit', hitAreaName: string): boolean;

    emit(event: 'motion', group: string, index: number): boolean;
}

class Live2DSprite extends Container {
    id!: number;

    textures: Texture[];

    texturesBound: boolean[];

    // temporary 4x4 matrix
    // prettier-ignore
    modelTransform = new Float32Array([
        1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1,
    ]);

    highlightCover?: Sprite;

    static async create(file: string | string[]) {
        const model = await Live2DModel.create(file);
        return new Live2DSprite(model);
    }

    private constructor(public model: Live2DModel) {
        super();

        this.textures = model.modelSettings.textures.map(file =>
            Texture.from(file, { resourceOptions: { crossOrigin: true } }),
        );
        this.texturesBound = Array(this.textures.length).fill(false);

        const originalFn = model.motionManager.startMotionByPriority.bind(model.motionManager);

        /**
         * @fires Live2DSprite#motion
         */
        model.motionManager.startMotionByPriority = async (group, index, priority) => {
            const started = await originalFn(group, index, priority);
            if (started) {
                this.emit('motion', group, index);
            }
            return started;
        };
    }

    highlight(enabled: boolean) {
        if (enabled) {
            if (!this.highlightCover) {
                this.highlightCover = new Sprite(Texture.WHITE);
                this.highlightCover.width = this.model.width;
                this.highlightCover.height = this.model.height;
                this.highlightCover.alpha = 0.3;

                this.addChild(this.highlightCover);
            }
            this.highlightCover.visible = true;
        } else if (this.highlightCover) {
            this.highlightCover.visible = false;
        }
    }

    /**
     * Performs hit action on sprite.
     *
     * @param x - The x position in world space.
     * @param y - The y position in world space.
     *
     * @fires Live2DSprite#hit
     */
    hit(x: number, y: number) {
        this.model
            .hitTest((x - this.position.x) / this.scale.x, (y - this.position.y) / this.scale.y)
            .forEach(hitAreaName => this.emit('hit', hitAreaName));
    }

    _calculateBounds() {
        this._bounds.addFrame(this.transform, 0, 0, this.model.width, this.model.height);
    }

    _render(renderer: Renderer) {
        // reset these renderer systems to make Live2D's drawing system compatible with Pixi
        renderer.batch.reset();
        renderer.geometry.reset();
        renderer.shader.reset();
        renderer.state.reset();

        this.model.internalModel.drawParamWebGL.setGL(renderer.gl);
        this.model.internalModel.drawParamWebGL.glno = (renderer as any).CONTEXT_UID;

        for (let i = 0, baseTexture; i < this.textures.length; i++) {
            baseTexture = this.textures[i].baseTexture;

            // don't render if any of textures is not ready
            if (!baseTexture.valid) {
                return;
            }

            if (!this.texturesBound[i]) {
                this.texturesBound[i] = true;

                // update the texture once it's ready, the binding location is not important
                renderer.gl.pixelStorei(WebGLRenderingContext.UNPACK_FLIP_Y_WEBGL, true);
                renderer.texture.bind(baseTexture, 0);
                renderer.gl.pixelStorei(WebGLRenderingContext.UNPACK_FLIP_Y_WEBGL, false);

                // bind the WebGLTexture generated by Pixi's TextureSystem
                // kind of ugly but this does the trick :/
                this.model.bindTexture(i, (baseTexture as any)._glTextures[(renderer as any).CONTEXT_UID].texture);
            }

            // manually update the GC counter so it won't be GCed
            (baseTexture as any).touched = renderer.textureGC.count;
        }

        const drawingScaleX = this.model.logicalWidth / renderer.gl.drawingBufferWidth;
        const drawingScaleY = -this.model.logicalHeight / renderer.gl.drawingBufferHeight; // flip Y

        const wt = this.transform.worldTransform;
        const transform = this.modelTransform;

        // put sprite's 3x3 matrix into model's 4x4 matrix
        transform[0] = wt.a * drawingScaleX;
        transform[1] = wt.c * drawingScaleY;
        transform[4] = wt.b * drawingScaleX;
        transform[5] = wt.d * drawingScaleY;
        transform[12] = wt.tx * drawingScaleX;
        transform[13] = wt.ty * drawingScaleY;

        this.model.update(Ticker.delta, Ticker.now, transform);

        // reset the active texture because it's been changed by Live2D's drawing system
        renderer.gl.activeTexture(WebGLRenderingContext.TEXTURE0 + renderer.texture.currentLocation);
    }
}

export default Live2DSprite;
